### ISSUE TITLE
[Errno 2] No such file or directory: '/usr/src/archiso_offline/airootfs/etc/systemd/system/reflector.service.d/archiso.conf'

### ISSUE THREAD

**Issue by layer7gmbh** [Torxed/archoffline#1]
Hi, 

it seems there are some more requirements to run this script:

```
python offline.py --mirrors=Sweden --packages="nano wget" --rebuild
Setting up a new build directory in /usr/src/archiso_offline
Copying the Arch ISO configuration releng to new build door /usr/src/archiso_offline.
Removed reflector service from ISO
Traceback (most recent call last):
  File "/usr/src/offline.py", line 136, in <module>
    setup_builddir(BUILD_DIR, pacman_temporary_database, pacman_package_cache_dir)
  File "/usr/src/offline.py", line 103, in setup_builddir
    modify_archiso_config_directory(main)
  File "/usr/src/offline.py", line 112, in modify_archiso_config_directory
    (main/"airootfs"/"etc"/"systemd"/"system"/"reflector.service.d"/"archiso.conf").unlink()
  File "/usr/lib/python3.9/pathlib.py", line 1343, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/archiso_offline/airootfs/etc/systemd/system/reflector.service.d/archiso.conf'
```

**Comment by Torxed** [comment]
The default ISO used to have (and still should have) the reflector service by default.
Did you remove that by any chance?

![2021-04-26-143943_747x110_scrot](https://user-images.githubusercontent.com/861439/116083933-84061700-a69d-11eb-802a-4ee98b0976eb.png)

Edit: I could make this optional by unlinking only if it exists ofc. Since I only unlink it to prevent online functionality to be enabled inside the booted ISO.

**Comment by layer7gmbh** [comment]
Hi, 

nope sorry, its there:

```
# pacman -Ss reflector
community/reflector 2021.4-1
    A Python 3 module and script to retrieve and filter the latest Pacman mirror list.

# python offline.py --mirrors=Sweden --packages="nano wget" --rebuild
Setting up a new build directory in /usr/src/archiso_offline
Copying the Arch ISO configuration releng to new build door /usr/src/archiso_offline.
Removed reflector service from ISO
Traceback (most recent call last):
  File "/usr/src/offline.py", line 136, in <module>
    setup_builddir(BUILD_DIR, pacman_temporary_database, pacman_package_cache_dir)
  File "/usr/src/offline.py", line 103, in setup_builddir
    modify_archiso_config_directory(main)
  File "/usr/src/offline.py", line 112, in modify_archiso_config_directory
    (main/"airootfs"/"etc"/"systemd"/"system"/"reflector.service.d"/"archiso.conf").unlink()
  File "/usr/lib/python3.9/pathlib.py", line 1343, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/archiso_offline/airootfs/etc/systemd/system/reflector.service.d/archiso.conf'

```
