### ISSUE TITLE
I'm really not sure what to call this.

### ISSUE THREAD

**Issue by FieryMewtwo** [Torxed/archoffline#6]
Running as directed I get

```fish
sataa@SusBook ~/D/a/archoffline-0.0.1 [1]> sudo python -m archoffline --mirrors=copy --packages="fish micro xorg-server xclip plasma-desktop konsole kate noto-fonts-emoji pipewire pipewire-pulse pipewire-alsa kwallet-pam kdeconnect sshfs networkmanager plasma-nm plasma-pa steam dolphin kio-admin ark steam firefox discord sddm sddm-kcm git base-devel spectacle neofetch" --verbose --template=releng
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/sataa/Desktop/archoffline-0.0.1/archoffline-0.0.1/archoffline/__init__.py", line 23, in <module>
    if archinstall.arguments.get('help', None):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'archinstall' has no attribute 'arguments'
```

**Comment by FieryMewtwo** [comment]
I'm just not sure what to do and I'm very tired because I'm not sleeping well :p

**Comment by Torxed** [comment]
Hi!

I assume you did `git clone git@github.com:Torxed/archoffline.git` and that works, but it will use the installed version of `archinstall` which is in a bit of a change process.

If you instead do `git clone --recursive git@github.com:Torxed/archoffline.git` it will also clone in a specific version of archinstall that should work fine with `archoffline` until I migrate the changes in here :)

**Comment by FieryMewtwo** [comment]
Ah, thank you
